# run: conda env create --file windows_environment.yml
# include new packages: conda env update --file windows_environment.yml
name: tudat-space
channels:
  - conda-forge
  - tudat-team
  - conda
dependencies:
- tudatpy
- anaconda
- nb_conda
- conda:
  - pytest>=3.0
  - nbconvert
- pip
- pip:
  # works for regular pip packages
  - pdflatex
  - testbook